### PR TITLE
Added extensionVersion to the Error message

### PR DESCRIPTION
**Pull request by masters3d**
I create the extension version programmatically and if I get this error, I want to know what is being supplied.

### CODE REVIEW

**Comment by jessehouwing** [comment]
Shouldn't ExtensionVersion be logged by default when you run with System.Debug=true?

**Comment by masters3d** [comment]
No, only the ExtensionVersion of the running extension shows when it starts up but not of the extensions that are being worked on.

**Comment by jessehouwing** [comment]
I just checked. When you enable `system.debug`=`true` each requested input is logged to the output.

**Comment by masters3d** [comment]
Are saying that `extensionVersion` should only show up in the logs when running in debug mode?

**Comment by jessehouwing** [comment]
Yes it should.

**Pull request closed without merging**
