### PR TITLE
Publish Visual Studio Extension task

### LINKED ISSUE #103: Visual Studio marketplace publish
When do you plan to have Visual Studio marketplace publish available?

### PR DESCRIPTION
**Pull request by onlyutkarsh**
- [x] New Publish Visual Studio Extension task
- [x] Re-use existing infrastructure, access tokens, service connections etc
- [x] Make the UI a close as possible to the existing Publish task
- [x] First version would publish as-is.
- [x] Set the correct Demands
- [x] Optionally use vswhere to detect the location of the Visual Studio SDK.
- [x] Fixes #103 
- [x] Clearly, mark the task as Preview.
- [ ] Create a Tool Installer task to install the vsix publisher executables and dependencies (Use the Nuget package to fetch the tools on demand)

This task uses [VSIXPublisher](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line?view=vs-2017) to publish Visual Studio extension to Marketplace.

**Screenshot:**

image

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109)

### CODE REVIEW

**Comment by jessehouwing** [comment]
Is looking pretty nice already. Some minor improvements and we van ship this!

**Comment by jessehouwing** [comment]
Looks like a rebase is also needed on Master.

**Comment by jessehouwing** [comment]
Will reply tomorrow.

**Comment by jessehouwing** [comment]
> _[BuildTasks/PublishVSExtension/package.json, line 22 at r1](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109#-LXKdZ0D1DQ962nj-dPS:-LXLIyGf-TmcrTB2iK_G:b-rjb8s4) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/935e0d7dd7d1ee1293733c9e266f92012cf0e576/BuildTasks/PublishVSExtension/package.json#L22)):_
> 
> Previously, jessehouwing (Jesse Houwing) wrote…
> If we will have Nod10 handler do I need to set the version to ~6?

Node10 is only supported ont he very latest Build agent against Azure DevOps and Azure DevOps Server 2019. In order to provide backwards compat we'd need to support Node 6 for some time to come. I haven't looked at the need to compile to both versions. The Node10 handler seems justa  bit faster. For this task it shoudn't matter much. Since you wrote it with Node 11, it should be node 10 compatible though.

> _[BuildTasks/PublishVSExtension/PublishVSExtension.ts, line 43 at r1](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109#-LXLJnzJBQOIy8ixlYHy:-LXLJnzJBQOIy8ixlYHz:beaax35) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/935e0d7dd7d1ee1293733c9e266f92012cf0e576/BuildTasks/PublishVSExtension/PublishVSExtension.ts#L43)):_
> 
> > ```
> > finally {
> >     console.info(`Logging out publisher '${publisher}'`);
> >     util.logout(publisher);
> > ```
> 
> Logging out user here.

Great, missed that.

> _[BuildTasks/PublishVSExtension/task.json, line 8 at r1](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109#-LXKg5XMDYdEMVEhY-ew:-LXLLe9XDJ4hFpHWI9IZ:bzgvw3s) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/935e0d7dd7d1ee1293733c9e266f92012cf0e576/BuildTasks/PublishVSExtension/task.json#L8)):_
> 
> Previously, jessehouwing (Jesse Houwing) wrote…
> I did not do this as the task is pretty stable. Doing it now though as this is our first release.

Right, that's the idea. Will remove the preview flag in the future.

> Previously, jessehouwing (Jesse Houwing) wrote…
> I think this task will run only on Windows, so is this required? Also as per `line()` docs, it wraps args internally anyway.

It will when you pass a `string[]` if you pass it a single line it assumes you did all the quoting. if any of the strings contain a space you'll get a weird error like "unexpected parametter HJF&*6sf8s67df78s".

> _[BuildTasks/PublishVSExtension/Utils.ts, line 72 at r1](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109#-LXKewl8DYJBDf8eUZtd:-LXLL1xG5xcl6MMsJK5l:bri532v) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/935e0d7dd7d1ee1293733c9e266f92012cf0e576/BuildTasks/PublishVSExtension/Utils.ts#L72)):_
> 
> Previously, jessehouwing (Jesse Houwing) wrote…
> Why is this required?

It's not entirely required, but right now each of the functions has the same two lines to setup the TR. I don't see any place where you need the vsixpath independently of the ToolRunner. So you can abstract away that implementation detail and reduce some of the repetitive stuff.

Storing the vsixinstaller path in a global variabel would also prevent us looking it up 6 times on disk.

> _[BuildTasks/PublishVSExtension/Utils.ts, line 73 at r1](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109#-LXKfCHlDpVk7M0uzMo5:-LXLL9uB2cm0heTx99EJ:btthkvk) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/935e0d7dd7d1ee1293733c9e266f92012cf0e576/BuildTasks/PublishVSExtension/Utils.ts#L73)):_
> 
> Previously, jessehouwing (Jesse Houwing) wrote…
> VSIXPublisher gets confused anyway with enclosed quotes etc. Tried already. I think at this moment its not necessary.

I understand, but the error message is probably much more cryptic.

> _[BuildTasks/PublishVSExtension/Utils.ts, line 87 at r1](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/109#-LXKfJnj7qh2FiMMs7U5:-LXLLPay1UfHnYAeEVXU:bl3orpf) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/935e0d7dd7d1ee1293733c9e266f92012cf0e576/BuildTasks/PublishVSExtension/Utils.ts#L87)):_
> 
> Previously, jessehouwing (Jesse Houwing) wrote…
> Same as above. VSIXPublisher does not take quotes in the command.

I understand, but the error message is probably much more cryptic.

**Comment by jessehouwing** [comment]
@onlyutkarsh do you have a very simple repo somewhere I can use as a test? I use my own VSTS-Ping-Task-Demo as my own test bench: https://github.com/jessehouwing/vsts-ping-task-demo

**Comment by onlyutkarsh** [comment]
> @onlyutkarsh do you have a very simple repo somewhere I can use as a test? I use my own VSTS-Ping-Task-Demo as my own test bench: https://github.com/jessehouwing/vsts-ping-task-demo

I use https://github.com/onlyutkarsh/InfoBarDemo - a small VS extension I created for a blog.

**Comment by onlyutkarsh** [comment]
@jessehouwing I have made the changes. I somewhat could not figure out how to leave general comment in Reviewable.io - Its UI confuses me :-)

**Comment by jessehouwing** [comment]
Will do a little more cleanup. thanks so much for all your efforts. Now to extend the build process to always fetch the latest vswhere.exe ;).

**Comment by jessehouwing** [comment]
Looks like we have out first bug report :).

**Pull request merged**
