### PR TITLE
Features/multi version

### PR DESCRIPTION
**Pull request by jessehouwing**
This is a work in progress.

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/vsts-extension-build-release-tasks/62)

### CODE REVIEW

**Comment by jessehouwing** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[BuildTasks/PublishExtension/vsixeditor.ts, line 93 at r1](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L6wqcl9zkQ-wF4UC6O-:-L6wqcl9zkQ-wF4UC6O0:b-rr7ovi) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/58f614fb3e92a9f87fd53f7c19b44c9c1a929430/BuildTasks/PublishExtension/vsixeditor.ts#L93)):*
> ew Promise<string>((resolve, reject) => {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>                     let tmpPath: string;
>                     temp.mkdir("vsixeditor", (ex, dirPath) => { tmpPath = dirPath; });
>                     resolve(tmpPath);
>                 })
</details>

This seems to not work as I thought it would be. Help wanted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62)*

**Comment by riezebosch** [comment]
where are the tests?!?!

---

Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[BuildTasks/Common/Common.ts, line 195 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71CTyBAYjBpzUrwWAF:-L71CTyBAYjBpzUrwWAG:b-czk1ue) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L195)):*
> ```XML
>  * @param  {(tfx:ToolRunner)=>void} cmd
>  */
> export async function runTfx(cmd: (tfx: ToolRunner) => void) {
> ```

async without await?

---

*[BuildTasks/Common/Common.ts, line 405 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71C4DtJ1nzBSl0-WcW:-L71C4DtJ1nzBSl0-WcX:byz6281) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L405)):*
> ```XML
> }
> 
> async function getTasksManifestPaths(manifestFile?: string): Promise<string[]> {
> ```

very long

---

*[BuildTasks/Common/Common.ts, line 428 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71Bftjb2qQXhZic9-q:-L71Bftjb2qQXhZic9-r:bhn73po) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L428)):*
> ```XML
>         tl.debug(`Found extension manifest: ${manifest}`);
>         const tasks = await getTaskPathContributions(manifest);
>         for (let t = 0; t < tasks.length; t++) {
> ```

tasks.forEach(_ => {})

---

*[BuildTasks/Common/Common.ts, line 433 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71BKhA_ywbaaZMdT5U:-L71BKhA_ywbaaZMdT5V:bdokk9z) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L433)):*
> ```XML
>             const taskRoot: string = path.join(rootFolder, task);
>             const rootManifest: string = path.join(taskRoot, "task.json");
>             if (fs.existsSync(rootManifest)) {
> ```

sync = smell, async/await

---

*[BuildTasks/Common/Common.ts, line 516 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71BsX9DhCZ0OUlpthA:-L71BsX9DhCZ0OUlpthB:b3v228i) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L516)):*
> ```XML
>         // If extension version specified, let's search for build tasks
>         if (extensionVersion) {
>             // Extract version parts Major, Minor, Patch
> ```

Extract to method instead of comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-:-L71CM3_4Fc-WsdEnsAw:b-57jctw)*

**Comment by jessehouwing** [comment]
Yeah... Fun, eh :). And retroactively putting them in is a nightmare.

---

Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[BuildTasks/Common/Common.ts, line 195 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71CTyBAYjBpzUrwWAF:-L71EDeLRCmagVgmjJOl:bbkcic9) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L195)):*
<details><summary><i>Previously, riezebosch (Manuel Riezebosch) wrote…</i></summary><blockquote>

async without await?
</blockquote></details>

I believe the PublishPackage.ts fails as long as that's out, as it's actually calling all kinds of async stuff through a delegate,

---

*[BuildTasks/Common/Common.ts, line 428 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71Bftjb2qQXhZic9-q:-L71DlEn-8HXzAU-1Pi4:bvqtyxy) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L428)):*
<details><summary><i>Previously, riezebosch (Manuel Riezebosch) wrote…</i></summary><blockquote>

tasks.forEach(_ => {})
</blockquote></details>

Tried that. Doesn't work because loaded Node packages cause arrays to return custom properties and iterating through the array using foreach and others return bogus items.

---

*[BuildTasks/Common/Common.ts, line 433 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71BKhA_ywbaaZMdT5U:-L71DuZ0Bb-UdIXtphgq:be7woc8) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L433)):*
<details><summary><i>Previously, riezebosch (Manuel Riezebosch) wrote…</i></summary><blockquote>

sync = smell, async/await
</blockquote></details>

It's a bloody build task, everything runs sequentially anyway and the agent is *never* actually running multiple tasks in parallel 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-:-L71DRa8EKQ4WjcQK8rJ:bxyf4zx)*

**Comment by riezebosch** [comment]
Review status: 0 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[BuildTasks/Common/Common.ts, line 195 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71CTyBAYjBpzUrwWAF:-L73XCP-_Gul6bX6lZf6:be99a1c) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L195)):*
<details><summary><i>Previously, jessehouwing (Jesse Houwing) wrote…</i></summary><blockquote>

I believe the PublishPackage.ts fails as long as that's out, as it's actually calling all kinds of async stuff through a delegate,
</blockquote></details>

Shouldn't you be awaiting the cmd then? The PublishExtension is quite hard to read. Doing lots of stuff in a single method.

---

*[BuildTasks/Common/Common.ts, line 433 at r2](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62#-L71BKhA_ywbaaZMdT5U:-L73VnNnUNkZNDIUgYiz:b-ejfg78) ([raw file](https://github.com/microsoft/vsts-extension-build-release-tasks/blob/364ee02e059211d4be9215f58c0054d7a07e0c6c/BuildTasks/Common/Common.ts#L433)):*
<details><summary><i>Previously, jessehouwing (Jesse Houwing) wrote…</i></summary><blockquote>

It's a bloody build task, everything runs sequentially anyway and the agent is *never* actually running multiple tasks in parallel 
</blockquote></details>

Sure thing, but it _is_ the TypeScript/NodeJS approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/microsoft/vsts-extension-build-release-tasks/62)*

**Pull request merged**
