### PR TITLE
Adding support for onlyPatch updating of task versions

### PR DESCRIPTION
**Pull request by colindembovsky**

### CODE REVIEW

**Comment by jessehouwing** [comment]
Can we make it a little more advanced? The patch number will either be very
high this way as resetting is really not an option, not even when the
extension gets a new major version.

Since vsts only looks at major to cause breaking changes to be marked, can
you make it configurable which part of the version number is overwritten?
X. X. X,  2. X. X or 2. 4. X?

I suspect I'll set my own tasks to follow the 2.x.x format.

**Comment by colindembovsky** [comment]
@jessehouwing Done!

**Comment by jessehouwing** [comment]
I needed to clean up the uuidv5 stuff I had prepared and is no longer needed due to the most recent marketplace changes.

I've merged your changes into a new branch.

**Comment by jessehouwing** [comment]
Will test and merge with master in the coming days. Thanks @colindembovsky .

**Pull request closed without merging**
