### PR TITLE
Fix for multi-version task manifest searching

### PR DESCRIPTION
**Pull request by gregpakes**
Fix for https://github.com/Microsoft/vsts-extension-build-release-tasks/issues/83

### CODE REVIEW

**Comment by gregpakes** [comment]
This is a fix for issue 83.  I haven't tested this yet

**Comment by jessehouwing** [comment]
Can we make it `*/task.json` instead? sub-sub-folders is against the docs as far as I remember.

**Comment by gregpakes** [comment]
Makes sense! I’ll make the change

**Comment by gregpakes** [comment]
I see you’ve already done it!

**Comment by jessehouwing** [comment]
Yeah on a branch I'm working on. Not directly against master... Depending on time I may cherry pick.

**Pull request closed without merging**
